"use client";

import Link from "next/link";
import { useState } from "react";
import { evaluateAccess, type AccessProfile, type PlatformSnapshot, type WorkItem } from "@smart-epp/domain";
import { Money } from "@/components/shared/Money";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { usePlatform } from "@/features/platform/store/PlatformProvider";

const queueLabels = ["My Tasks", "My Approvals", "My Exceptions", "Team Queues", "Unassigned Work", "Notifications", "Escalations", "Delegations", "Recently Viewed"] as const;
export type WorkbenchQueue = { label: typeof queueLabels[number]; items: WorkItem[] };
export function buildWorkbenchQueues(snapshot: PlatformSnapshot, profile: AccessProfile): WorkbenchQueue[] { const items = snapshot.workItems; const mine = items.filter((item) => item.owner === profile.userId); const by = (predicate: (item: WorkItem) => boolean) => items.filter(predicate); return [{ label: "My Tasks", items: mine }, { label: "My Approvals", items: by((item) => item.state === "PENDING") }, { label: "My Exceptions", items: by((item) => item.state === "OVERDUE" || item.state === "REJECTED") }, { label: "Team Queues", items }, { label: "Unassigned Work", items: by((item) => !item.owner) }, { label: "Notifications", items: by((item) => item.state === "PENDING") }, { label: "Escalations", items: by((item) => item.state === "OVERDUE") }, { label: "Delegations", items: [] }, { label: "Recently Viewed", items: items.slice(0, 3) }]; }
export const getWorkbenchApprovalAccess = (profile: AccessProfile, initiatedBy: string) => evaluateAccess({ profile, module: "ORDERS_APPROVALS", action: "APPROVE", initiatedBy });
export function Workbench({ initialQueue }: { initialQueue?: string }) { const { snapshot, activeProfile } = usePlatform(); const queues = buildWorkbenchQueues(snapshot, activeProfile); const requested = initialQueue ? queueLabels.findIndex((label) => label.toLowerCase().replaceAll(" ", "-") === initialQueue) : -1; const [active, setActive] = useState(requested >= 0 ? requested : 0); const queue = queues[active]!; const approval = getWorkbenchApprovalAccess(activeProfile, "another-maker"); return <section className="operations-workbench" aria-labelledby="workbench-title"><header className="page-heading"><div><span className="eyebrow">Source-backed operational queues</span><h1 id="workbench-title">Workbench</h1><p>Profile changes actions and default queue context only; all queue categories remain available.</p></div><StatusBadge status="INFO" label={activeProfile.roleKeys.join(", ")} /></header><div role="tablist" aria-label="Workbench queues" className="command-tabs">{queues.map((item, index) => <button key={item.label} role="tab" aria-selected={active === index} onClick={() => setActive(index)}>{item.label}</button>)}</div><div role="tabpanel" className="operations-table-scroll"><table><thead><tr><th>Work item</th><th>Owner / due</th><th className="align-right">Impact (INR)</th><th>State</th><th>Action</th></tr></thead><tbody>{queue.items.map((item) => <tr key={item.id}><td><Link href={item.href}>{item.title}</Link><br /><span className="text-muted">{item.id}</span></td><td>{item.owner || "Unassigned"}<br /><time dateTime={item.dueDate}>{item.dueDate}</time></td><td className="align-right"><Money paise={item.financialImpactPaise} /></td><td><StatusBadge status={item.state === "OVERDUE" ? "CRITICAL" : item.state === "REJECTED" ? "REJECTED" : "ATTENTION"} label={item.state} /></td><td><button disabled={!approval.allowed} aria-describedby={!approval.allowed ? "iam-permission" : undefined}>Approve</button></td></tr>)}</tbody></table>{queue.items.length === 0 && <div className="operations-empty-state"><h2>No source-backed records in this queue</h2><p>This deterministic snapshot has no qualifying work items.</p></div>} {!approval.allowed && <span id="iam-permission" className="sr-only">Requires IAM permission</span>}</div></section>; }
